### ISSUE TITLE
Are downloading JSs duplicated?

### ISSUE THREAD

**Issue by hajimehoshi** [dave/play#2]
From my observation of https://play.jsgo.io/github.com/hajimehoshi/ebiten/examples/flappy, I think the playground downloads many (semantically) duplicated files: *.js and *.a. I guess *.js are for the playground itself, and *.a are for compilation results of dependencies, right?

Now I'm concerned about downloading time is long on playground especially on mobile phone. Would it be possible to reduce the time by removing duplications?

**Comment by dave** [comment]
Yeah you're seeing two steps combined:

First you're seeing the playground itself loading, with the minified JS files from the jsgo.io compilation process. You can see the playground loading without any contents by opening [this](https://play.jsgo.io/6923c22a946e554b6eb7e8777b30b2e4961fe598) in an incognito window. It's a pretty complex project with ~150 Go packages in it's dependency tree, and if your cache is empty it'll download ~1.9MB of minified, gzipped JS.

Second you're seeing the playground initialise itself from the flappy package in the URL. It requests the initialisation from the server, which does a `git fetch` on all the dependencies of your flappy package. All the dependencies are compiled server side, and the GopherJS binary Archive files (with un-minified JS contained in them) are delivered to the client in two ways: 

1) the standard library packages are downloaded by HTTP from pkg.jsgo.io (so they can be cached) 
2) the non-standard library packages are sent as gzipped binaries inside the websocket connection. 

Since flappy is a pretty big app with ~130 packages in it's dependency tree, the total download with an empty cache is around 12MB.

I'll continue to work on ways to make it faster, but the playground isn't really intended to be super high performance. I certainly wouldn't recommend it to be used on a mobile device! If you're expecting your app to load in the quickest time, deploy it to jsgo.io using the playground or compile it with compile.jsgo.io.

**Comment by dave** [comment]
It might be possible to strip some of the contents out from the pre-compiled standard library archive files, while still allowing GopherJS to use them in the dependency tree when compiling client side... We shouldn't really need the JS that's stored inside the standard library archive files because we have that all (potentially in the browser cache) on pkg.jsgo.io. When I get some more time I'll have a deeper dig into the GopherJS internals to see if there's any more easy wins.

**Comment by dave** [comment]
... and perhaps the default should be to use the minified version of all the archive files in the playground... It's pretty uncommon to be digging into the actual JS code, and a tick-box to toggle it might make more sense than using un-minified by default. I'll add that to the to-do list.

**Comment by dave** [comment]
@hajimehoshi Great progress today! I've stripped all the non-essential junk out of the standard library archive files, and the client requests both the stripped archive file, and the rendered JS file. These are the same rendered JS files that we use in jsgo.io, so more likely to benefit from a browser cache hit. Also the combination of rendered JS file + stripped archive file is significantly smaller than the full archive file. 

Additionally I've defaulted to using minified JS in the playground (there's now an option to turn it on and off in the menu).

Together, these changes reduce the total initialisation download of your flappy app in the playground from ~12MB to ~3.6MB.

Let me know how you get on...

**Comment by hajimehoshi** [comment]
Great job!

Hmm, I've opened the flappy again but found some alerts:

```
Get https://pkg.jsgo.io/runtime.862690a6e22bb9d83a495b05ae0a6de473c0b502.js: net/http: fetch() failed: TypeError: Failed to fetch
```

**Comment by dave** [comment]
Can you try again and take a look in the `network` tab of the inspector? It might give you more information why it failed... I don't see the same errors here...

**Comment by hajimehoshi** [comment]
As cache is disabled on the developer tools, now I can't see any alerts... Maybe cache was too old?

**Comment by hajimehoshi** [comment]
I've not taken benchmarks, but I feel the compilation speed is faster. Thank you!

**Comment by dave** [comment]
@hajimehoshi Another optimisation this afternoon... We now render the stripped Archive file and the JS to the CDN for all dependencies... Previous to this change, the standard library packages were pre-rendered but the non-standard-library packages were delivered gzipped in the websocket connection. The total page download in MB isn't very different, but it loads a lot quicker. In my testing, the flappy playground initialisation went from ~19sec to ~11sec!

Let me know how you get on!

**Comment by hajimehoshi** [comment]
Thanks!

On Flappy, there are two errors:

```
VM592:1477 Uncaught TypeError: Cannot read property 'constructor' of undefined
    at Object.FZ [as TypeOf] (<anonymous>:1:175472)
    at Object.$packages.fmt.AN.ptr.doPrint (<anonymous>:1:125756)
    at Object.AW [as Sprint] (<anonymous>:1:71830)
    at Object.S [as Fatal] (<anonymous>:1:14564)
    at AH (<anonymous>:4:2858)
    at $init (<anonymous>:7:2127)
    at $goroutine (<anonymous>:1468:19)
    at $runScheduled (<anonymous>:1508:7)
    at $schedule (<anonymous>:1524:5)
    at $go (<anonymous>:1500:3)
    at <anonymous>:142:3
    at Object.$packages.honnef.co/go/js/dom.DM.ptr.AppendChild (dom.c529a906224889d31dc6a5317655060e485084f0.js:1)
    at Object.$packages.github.com/dave/play/stores.BK.ptr.compile [as $blk] (stores.76c34c1fe5e6a9575bf80613e8e95c71a05a5023.js:1)
    at Object.$packages.github.com/dave/play/stores.BK.ptr.Handle [as $blk] (stores.76c34c1fe5e6a9575bf80613e8e95c71a05a5023.js:1)
    at Object.$b [as $blk] (flux.13c53c0d92f6235e71336388322d558168c96387.js:1)
    at e (prelude.9fa5354baf5360cd05ba2ef218170de88191c7ee.js:1)
    at r (prelude.9fa5354baf5360cd05ba2ef218170de88191c7ee.js:1)
    at $runScheduled (prelude.9fa5354baf5360cd05ba2ef218170de88191c7ee.js:1)
    at $schedule (prelude.9fa5354baf5360cd05ba2ef218170de88191c7ee.js:1)
    at prelude.9fa5354baf5360cd05ba2ef218170de88191c7ee.js:1
    at $close (prelude.9fa5354baf5360cd05ba2ef218170de88191c7ee.js:1)
    at stores.76c34c1fe5e6a9575bf80613e8e95c71a05a5023.js:1
    at e.$externalizeWrapper.e.$externalizeWrapper (prelude.9fa5354baf5360cd05ba2ef218170de88191c7ee.js:1)
```

```
VM592:1409 Uncaught Error: audio: context is already created
    at $callDeferred (<anonymous>:1409:17)
    at $panic (<anonymous>:1448:3)
    at Object.S [as NewContext] (<anonymous>:1:11744)
    at AH (<anonymous>:4:2711)
    at $init (<anonymous>:7:2127)
    at $goroutine (<anonymous>:1468:19)
    at $runScheduled (<anonymous>:1508:7)
    at $schedule (<anonymous>:1524:5)
    at queueEntry (<anonymous>:1590:5)
    at $close (<anonymous>:1613:5)
    at <anonymous>:1:11184
    at <anonymous>:1532:5
```

**Comment by dave** [comment]
Eek! Thanks... I'll investigate tomorrow.

**Comment by dave** [comment]
Spent a couple of hours this morning working through this bug and couldn't get to the bottom of it, so I've reverted to the previous version. I'll continue looking into soon.

**Comment by dave** [comment]
OK I fixed that bug and re-deployed the optimisations. The bug was in my function that strips the unneeded parts from the GopherJS archive files, meaning the compiler couldn't tell if a function was blocking. All fixed now and it should be quite a bit faster to load.

**Comment by hajimehoshi** [comment]
Yeah, I think compiling is way faster than the initial state. Thank you so much!

**Comment by dave** [comment]
I've got one more optimisation to do before I call this one done...

**Comment by dave** [comment]
OK so I think we're as optimized as we're going to be for a while... I'll close this issue but feel free to re-open if you have more questions.
