### ISSUE TITLE
Missing messages package - doesn't compile

### ISSUE THREAD

**Issue by telecoda** [dave/play#4]
Current master doesn't compile

Looks like its missing the `messages` package in the jsgo repo?

actions/actions.go:6:2: cannot find package "github.com/dave/jsgo/server/messages"

I pulled the latest code on both repos.

**Comment by dave** [comment]
Oh yeah right I'm in the middle of a massive refactor right now... I was pushing to the play repo using another branch because I didn't want anyone to be able to recompile it broken at compile.jsgo.io/github.com/dave/play (the front-end of play.jsgo.io just blindly uses the latest successfully compiled version even if it's broken - not ideal!)... 

However, as you've realised I've broken play by pushing refactored code to the jsgo repo master branch. Oops. I'm in the middle of a trek in the Nepal backcountry, so coding mostly offline and git pushing when I get internet... Should have put used branches in all the repos really. If you check out the `refactor` branch of the play repo you might have more luck... But as I say I'm in the middle of a period of frenzied development so you might have problems getting it running. 

Plus I haven't (yet) spent any time optimising this project for anyone else to develop on... 

Here's a tip: it's got a pretty good "offline" mode for development without an internet connection - it pulls code from your local GOPATH instead of the git repos on the internet, and stores data / assets in a temporary folder instead of using GCS services. Use build tags `dev local` to enable that. You'll need to edit [generate.go](https://github.com/dave/jsgo/blob/master/generate.go) to add those build tags to the `initialise.go` command before running `go generate`... that way it'll store all the assets locally instead of using GCS. Oh, you'll need to update [this too](https://github.com/dave/jsgo/blob/master/config/constants.go#L8) with the temp dir. 

As I said this isn't really set up for anyone else to develop on, but I'm happy to help you hack!

**Comment by telecoda** [comment]
Awesome thanks I'll take a look.

It looks great so far. I'm seeing if I can run it locally to create a fantasy virtual console in Go like Pico8.

**Comment by dave** [comment]
BTW you also need the `norwfs` tag, so to get it running locally the right command is:

`go run -tags "norwfs dev local" "$GOPATH/src/github.com/dave/jsgo/server/main/main.go"`

**Comment by dave** [comment]
Then `localhost:8080` will be the playground.

**Comment by telecoda** [comment]
Got it working :)

Checked out the `refactor` branch.

Generated the local assets using: 
`go run -tags="dev local" ./initialise/initialise.go`

Created a local CORS compatible fileserver to host the local assets on port 8092.

https://gist.github.com/telecoda/0439695fd07ed207082c3f7bcc78b386

Seems to run ok offline. Enjoy your trip

**Comment by dave** [comment]
You shouldn’t need to do that... when you run the server in local mode it should start file servers for the local buckets...

**Comment by telecoda** [comment]
Yeah I realised that this morning. Only been dipping in/out the code on the way to work.

**Comment by dave** [comment]
Hey I just did a deploy, so what's running on `{play|compile}.jsgo.io` is what's in the master branch now. I'll try to keep the master branches in better shape in future!
